### PR TITLE
No need to know the tekton namespace

### PR DESCRIPTION
**Pull request by csantanapr**

### CODE REVIEW

**Review by seansund — APPROVED** [review]
LGTM

**Review by seansund — CHANGES_REQUESTED** [review]
Could you remove `tekton_namespace` from test/stages/stage2-tekton.tf as well?

**Comment by csantanapr** [comment]
@seansund it's already removed from `/tests/stages/stage2-tekton.tf`
Here https://github.com/ibm-garage-cloud/terraform-tools-tekton-resources/pull/5/files#diff-d19caadf91f229ab4f6f307c40ddcf91L15

**Review by seansund — COMMENTED** [review]
LGTM

**Comment by csantanapr** [comment]
super seed by #18

**Pull request closed without merging**
